import { useEffect, useRef, useState } from "react";
type Level = "small" | "medium" | "large"; type Cell = [number, number]; type Algorithm = "bfs" | "dfs" | "dijkstra" | "astar";
type Search = { visited: Cell[]; path: Cell[] };
const sizes: Record<Level, number> = { small: 25, medium: 39, large: 53 };
const id = (cell: Cell) => `${cell?.[0] ?? -1},${cell?.[1] ?? -1}`; const same = (a?:Cell,b?:Cell) => !!a&&!!b&&a[0]===b[0]&&a[1]===b[1];
const directions: Cell[] = [[1,0],[-1,0],[0,1],[0,-1]];
function fixedMaze() { let seed=123456; return generate(25,()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}); }
function generate(n:number, random=Math.random) { const maze=Array.from({length:n},()=>Array(n).fill(1)), stack:Cell[]=[[1,1]]; maze[1][1]=0; while(stack.length){const [r,c]=stack[stack.length-1], next=directions.map(([a,b])=>[r+a*2,c+b*2] as Cell).filter(([a,b])=>a>0&&b>0&&a<n-1&&b<n-1&&maze[a][b]); if(!next.length){stack.pop();continue}const [a,b]=next[Math.floor(random()*next.length)];maze[(r+a)/2][(c+b)/2]=0;maze[a][b]=0;stack.push([a,b]);}for(let r=1;r<n-1;r++)for(let c=1;c<n-1;c++){if(maze[r][c]!==1||random()>.18)continue;const vertical=maze[r-1][c]===0&&maze[r+1][c]===0,horizontal=maze[r][c-1]===0&&maze[r][c+1]===0;if(vertical||horizontal)maze[r][c]=0;}return maze; }
function run(maze:number[][], start:Cell, goal:Cell, kind:Algorithm):Search { const open:{p:Cell;g:number}[]=[{p:start,g:0}], parent=new Map<string,string>(), seen=new Set<string>(), visited:Cell[]=[]; const valid=([r,c]:Cell)=>r>=0&&c>=0&&r<maze.length&&c<maze.length&&!maze[r][c]; while(open.length){if(kind==="dijkstra"||kind==="astar")open.sort((a,b)=>a.g+(kind==="astar"?Math.abs(a.p[0]-goal[0])+Math.abs(a.p[1]-goal[1]):0)-b.g-(kind==="astar"?Math.abs(b.p[0]-goal[0])+Math.abs(b.p[1]-goal[1]):0));const node=kind==="dfs"?open.pop()!:open.shift()!, key=id(node.p);if(seen.has(key))continue;seen.add(key);visited.push(node.p);if(same(node.p,goal)){const path:Cell[]=[];let cursor=key;while(cursor){const [r,c]=cursor.split(",").map(Number);path.unshift([r,c]);cursor=parent.get(cursor)||"";}return{visited,path};}directions.forEach(([r,c])=>{const next:[number,number]=[node.p[0]+r,node.p[1]+c], nextKey=id(next);if(valid(next)&&!seen.has(nextKey)){if(!parent.has(nextKey))parent.set(nextKey,key);open.push({p:next,g:node.g+1});}});}return{visited,path:[]}; }
export default function MazePathfindingDemo(){const [level,setLevel]=useState<Level>("small"),[maze,setMaze]=useState(fixedMaze),[player,setPlayer]=useState<Cell>([1,1]),[moves,setMoves]=useState(0),[algorithm,setAlgorithm]=useState<Algorithm>("astar"),[speed,setSpeed]=useState(25),[frontier,setFrontier]=useState<Cell[]>([]),[visited,setVisited]=useState<Cell[]>([]),[path,setPath]=useState<Cell[]>([]),[result,setResult]=useState<{explored:number;length:number}|null>(null),[compare,setCompare]=useState<{name:string;explored:number;length:number}[]>([]),[message,setMessage]=useState("Use arrow keys, tap adjacent open cells, then let an algorithm explore the same maze."), timer=useRef<number>();const goal:Cell=[maze.length-2,maze.length-2]; const open=([r,c]:Cell)=>r>=0&&c>=0&&r<maze.length&&c<maze.length&&!maze[r][c];
 const newMaze=(next=level)=>{window.clearInterval(timer.current);const grid=generate(sizes[next]);setMaze(grid);setPlayer([1,1]);setMoves(0);setVisited([]);setFrontier([]);setPath([]);setResult(null);setCompare([]);setMessage("Fresh solvable maze ready.");};
 const move=(next:Cell)=>{if(Math.abs(next[0]-player[0])+Math.abs(next[1]-player[1])!==1||!open(next))return;setPlayer(next);setMoves(m=>m+1);if(same(next,goal))setMessage("You reached the goal! Now compare your route with an algorithm.");};
 useEffect(() => {
   const onKeyDown = (event: KeyboardEvent) => {
     const offsets: Record<string, Cell> = { ArrowUp: [-1, 0], ArrowDown: [1, 0], ArrowLeft: [0, -1], ArrowRight: [0, 1] };
     const offset = offsets[event.key];
     if (!offset) return;
     event.preventDefault();
     move([player[0] + offset[0], player[1] + offset[1]]);
   };
   window.addEventListener("keydown", onKeyDown);
   return () => window.removeEventListener("keydown", onKeyDown);
 });
 const animate=()=>{window.clearInterval(timer.current);const found=run(maze,[1,1],goal,algorithm);setVisited([]);setFrontier([]);setPath([]);setResult(null);let i=0;timer.current=window.setInterval(()=>{if(i>=found.visited.length){window.clearInterval(timer.current);setPath(found.path);const next={explored:found.visited.length,length:Math.max(0,found.path.length-1)};setResult(next);setCompare(rows=>[...rows.filter(r=>r.name!==algorithm),{name:algorithm,...next}]);setMessage(`${algorithm.toUpperCase()} finished. ${next.explored} states explored.`);return;}setVisited(old=>[...old,found.visited[i]]);setFrontier(found.visited.slice(i+1,i+5));i++;},Math.max(8,220-speed*2));};
 const pause=()=>{window.clearInterval(timer.current);setMessage("Animation paused. Choose Run search to restart this algorithm.");};
 const classes=(p:Cell)=>{const wall=maze[p?.[0]]?.[p?.[1]] ?? 1;return[same(p,goal)?"maze-goal":same(p,player)?"maze-player":path.some(x=>same(x,p))?"maze-path":frontier.some(x=>same(x,p))?"maze-frontier":visited.some(x=>same(x,p))?"maze-visited":wall?"maze-wall":"maze-open"].join(" ");};
 return <article className="sandbox-card maze-card"><div className="sandbox-card-copy"><span>PATHFINDING CHALLENGE</span><h3>Maze pathfinding lab</h3><p>Find the goal yourself, then watch real searches explore the identical maze.</p></div><div className="sandbox-controls"><label>Difficulty <select value={level} onChange={e=>{const next=e.target.value as Level;setLevel(next);newMaze(next)}}><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></select></label><button type="button" onClick={()=>newMaze()}>New maze</button><label>Algorithm <select value={algorithm} onChange={e=>setAlgorithm(e.target.value as Algorithm)}><option value="bfs">Breadth first search</option><option value="dfs">Depth first search</option><option value="dijkstra">Dijkstra</option><option value="astar">A* · Manhattan</option></select></label><label>Speed <input type="range" min="1" max="100" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label><button type="button" onClick={animate}>Run search</button><button type="button" onClick={pause}>Pause</button></div><div className="maze-grid" style={{gridTemplateColumns:`repeat(${maze.length}, 1fr)`}} aria-label="Interactive maze. Use arrow keys or select an adjacent open cell.">{maze.map((row,r)=>row.map((_,c)=><button key={`${r}-${c}`} type="button" className={classes([r,c])} onClick={()=>move([r,c])} aria-label={`Row ${r+1}, column ${c+1}`}>{same([r,c],player)?"P":same([r,c],goal)?"G":""}</button>))}</div><div className="metric-row"><b>Your moves: {moves}</b><b>States explored: {result?.explored??"–"}</b><b>Path length: {result?.length??"–"}</b></div><p className="sandbox-note" role="status">{message} {result&&moves?moves===result.length?"You matched the shortest route!":`${Math.max(0,moves-result.length)} moves over the algorithm.`:""}</p>{compare.length>1&&<p className="sandbox-note">Comparison: {compare.map(row=>`${row.name.toUpperCase()} ${row.explored} states / ${row.length} steps`).join(" · ")}</p>}</article>;}
